# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Nair
tagline:          'The Blog of Nair'
description:      'My experience as a part-time sysadmin and other stuff.'
url:              https://aadityanair.ml
baseurl:          /

author:
  name:           'Aaditya M Nair'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0
gems: [jekyll-paginate]

github:
  repo:           https://github.com/AadityaNair
