#Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Nair
tagline:          'The Blog of Nair'
description:      'My experience as a part-time sysadmin and other stuff'
url:              https://aadityanair.ml
baseurl:          /

author:
  name:           'Aaditya M Nair'

defaults:
    -
        scope:
            path: ""
            type: 'posts'
        values:
            comments: true
            is_post: true

paginate:         4

plugins: 
    - jekyll-paginate
    - jekyll-sitemap

github:
  repo:           https://github.com/AadityaNair
linkedin:         https://www.linkedin.com/in/aadityanair/
